# Full project: https://gitlab.com/pages/plain-html
image: alpine:latest

pages:
  stage: deploy
  script:
  - mkdir public/script
  - cp *.user.js public/script/
  artifacts:
    paths:
    - public
  only:
  - master
