build_image:
  before_script:
    - Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  script:
    - Write-Host "Setup AU module"
    - ./setup/au_setup.ps1
    - Write-Host "Start updating packages"
    - cd au
    - if(Invoke-WebRequest -Uri "https://github.com/htacg/tidy-html5/releases") { Write-Host "Working" } else {Write-Host "Err" }
    - ./update_all.ps1
  #  - ./update.ps1
  after_script:
    - md upload
    - Get-ChildItem -Path ./ -Include *.nupkg -Recurse -File | Move-Item -Destination ./upload/
  artifacts:
    paths:
        - upload/
    expire_in: 1 week
  tags:
    - shared-windows
    - windows
