 build_image:
  before_script:
    - Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    - git remote set-url origin https://tunisiano187:${Gitlab_api}@gitlab.com/chocolatey-packages/automatic-updating.git
    - git config --global user.email 'helpdesk.choc@gmail.com'
    - git config --global user.name 'tunisiano'
  script:
    - Write-Host "Setup AU module"
    - ./setup/au_setup.ps1
    - Write-Host "Start updating packages"
    - cd au
    - ./invoke-setup.ps1
    - ./update_all.ps1
  #  - ./update.ps1
  after_script:
    - md upload
    - Get-ChildItem -Path ./ -Include *.nupkg -Recurse -File | Move-Item -Destination ./upload/
    - Get-ChildItem -Path ./ -Include Update-AUPacakges.md -Recurse -File | Move-Item -Destination ./upload/
    - git checkout -B master
    - git add -u :/
    - git commit -m '[skip ci] commit from CI runner'
    - git push --follow-tags origin master
  artifacts:
    paths:
        - upload/
    expire_in: 1 week
  tags:
    - shared-windows
    - windows
