 build_image:
  before_script:
    - Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    - git remote set-url origin https://tunisiano187:${Gitlab_api}@gitlab.com/chocolatey-packages/automatic-updating.git
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name $GITLAB_USER_LOGIN
  script:
    - Write-Host "Setup AU module"
    - ./setup/au_setup.ps1
    - Write-Host "Setup requisites"
    - ./setup/requisites.ps1
    - Write-Host "Updating Packages.md"
    - ./scripts/ListPackages.ps1
    - Write-Host "Start updating packages"
    - install-module Wormies-AU-Helpers
    - tosend/try.ps1
    - Write-host "Check broken package"
    - tools/looknewer.ps1
    - cd au
    - ./invoke-setup.ps1
    - ../scripts/Update-PackageSourceUrl.ps1 -GithubRepository "tunisiano187/Chocolatey-packages" -UseStopwatch
    - ../scripts/Update-IconUrl.ps1 -Quiet -GithubRepository "tunisiano187/Chocolatey-packages" -UseStopwatch -Optimize
    - ./update_all.ps1
  #  - ./update.ps1
  after_script:
    - md upload
    - Get-ChildItem -Path ./ -Include *.nupkg -Recurse -File | Move-Item -Destination ./upload/
    - Get-ChildItem -Path ./ -Include Update-AUPacakges.md -Recurse -File | Move-Item -Destination ./upload/
    - Get-ChildItem -Path ./ -Include update_info.xml -Recurse -File | Move-Item -Destination ./upload/
    #- git checkout -B master
    #- git add -u :/
    #- git commit -m '[skip ci] commit from CI runner'
    #- if(git log origin/master..master) { git push origin master }
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  artifacts:
    paths:
        - upload/
    expire_in: 1 week
  tags:
    - shared-windows
    - windows
