pages:
  stage: deploy
  script:
  - mkdir public/script
  - cp *.user.js public/script/
  - sed -i "s/.version./$(cat public/script/WME-send-to-slack.user.js | grep @version | tail -c 14 | cut -c-13)/g" public/index.html
  - $features = cat public/features.html | grep <li> | wc -l
  - sed -i "s/requested-*-success.svg/requested-$($features)-success.svg/g" public/index.html
  artifacts:
    paths:
    - public
  only:
  - master