stages:
  - release
  
publishing:
    stage: release
    script: 
         - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
         - eval $(ssh-agent -s)
         - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
         - git config --global user.email "Tunisiano18@wazebelgium.be"
         - git config --global user.name "Tunisiano18"
         - echo 'git tag -a $(cat WME-send-to-slack.user.js | grep @version | tr -s " " | cut -d " " -f3) -m "Version created by Tunisiano18"'
         - git remote set-url origin git@gitlab.com:WMEScripts/wme-send-to-slack-public.git
         - GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git push origin HEAD:master
        # - git push origin $(cat WME-send-to-slack.user.js | grep @version | tr -s " " | cut -d " " -f3)
        # - git push origin :refs/tags/v4